---
stages:
  - name: prepare-env
    exec:
      - $NOTIFY --data-urlencode "status=2" --data-urlencode "current-stage=$STAGE"
      - git clone -b $FLEXIO_SCRIPTS_BRANCH $FLEXIO_SCRIPTS $WORKSPACE/flexio-ci-scripts && export PATH=$PATH:$WORKSPACE/flexio-ci-scripts/bin
      - docker pull $CI_TOOLS_IMAGE
      - mkdir -p $WORKSPACE/.m2

  - name: build
    timeout: 15
    exec:
      - $NOTIFY --data-urlencode "status=2" --data-urlencode "current-stage=$STAGE"
      - $MVN clean install

  - name: deploy
    timeout: 15
    exec:
      - $NOTIFY --data-urlencode "status=2" --data-urlencode "current-stage=$STAGE"
      - $MVN deploy  -DskipTests

onSuccess:
  - name: metadata
    exec:
      - $UPLOAD_PROJECT_METADATA
      - $TRIGGER_DOWNSTREAM
  - name: notify-flexio
    exec:
      - $NOTIFY --data-urlencode "status=0" --data-urlencode "current-stage="

onError:
  - name: notify-flexio
    exec:
      - $NOTIFY --data-urlencode "status=1" --data-urlencode "current-stage="



env:
  - FLEXIO_SCRIPTS: git@github.com:Flexio-corp/flexio-ci-scripts.git
  - FLEXIO_SCRIPTS_BRANCH: master
  - CI_TOOLS_IMAGE: codingmatters/ci-tools:0.0.1-SNAPSHOT
  - MVN: docker run --rm -v $SRC:/src -v $WORKSPACE/.m2:/root/.m2 -v $WORKSPACE/secrets/settings.xml:/root/.m2/settings.xml $CI_TOOLS_IMAGE mvn -B -Ddocker.registry=registry.containers.ovh.net
  - NOTIFY: curl -G "https://my.flexio.io/channelApi/flexHttpInOut/59d3a0105d443519843d0496/5adf40aededdbb452368cfca" --data-urlencode "repository=$REPOSITORY" --data-urlencode "branch=$BRANCH" --data-urlencode "pipeline-id=$PIPELINE_ID"
  - PIPELINES_URL: http://master.ci.flexio.io:6545/pipelines
  - DEPENDENCIES_URL: http://master.ci.flexio.io:6545/dependencies
  - UPLOAD_PROJECT_METADATA: docker run --rm  --env REPOSITORY_ID="$REPOSITORY_ID" --env REPOSITORY="$REPOSITORY" --env CHECKOUT_SPEC="$CHECKOUT_SPEC" -v $SRC:/src -v $WORKSPACE/.m2:/root/.m2 -v $WORKSPACE/secrets/settings.xml:/root/.m2/settings.xml -v $WORKSPACE/flexio-ci-scripts:/flexio-ci-scripts $CI_TOOLS_IMAGE /flexio-ci-scripts/bin/upload-project-metadata.sh $DEPENDENCIES_URL /src
  - TRIGGER_DOWNSTREAM: docker run --rm  --env REPOSITORY_ID="$REPOSITORY_ID" --env REPOSITORY="$REPOSITORY" --env CHECKOUT_SPEC="$CHECKOUT_SPEC" $CI_TOOLS_IMAGE /usr/local/bin/trigger-downstream.sh $DEPENDENCIES_URL $PIPELINES_URL $REPOSITORY_ID "$REPOSITORY" "$CHECKOUT_SPEC"

secrets:
  - name: settings.xml
    content: $SRC/.poom-ci-pipeline/settings-oss.xml.enc
    as: file
